apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-vnom
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0075-tenant/tkrw-pr712-0075-0075-app/devfile-sample-vnom@sha256:ed5df406d8ecaf3eac034d33ff390ad101b2c3686c9fc272cce30b6fffac1178
        name: my-nodejs
        resources: {}
status: {}
